### ISSUE TITLE
Add support for JSX and TSX

### ISSUE THREAD

**Issue by Indeedornot** [Flyrell/html-attribute-folder#1]
Hi! 
Would It be possible to add suport for tsx and jsx files? Would be really useful for using tailwind with react
I checked source code for a list of supported extensions to try to see how simply changing it would affect the behavior, however i did not find anything

**Comment by denisborovikov** [comment]
It would be really helpful for MUI 5 with React as well to fold `sx` props https://mui.com/system/getting-started/the-sx-prop/

**Comment by denisborovikov** [comment]
For those who interested, I "made" a plugin using LivePlugin https://gist.github.com/denisborovikov/e5241c93f0dd9007b3fdb00d8c6e125b

**Comment by tscharke** [comment]
I made an update version of @denisborovikov 's plugin using LivePlugin

https://gist.github.com/tscharke/4afa1120828cc552f7b2c5470738231e

**Comment by tscharke** [comment]
For this I created a [fork](https://github.com/tscharke/html-attribute-folder) and make it runnable 👉[https://github.com/tscharke/html-attribute-folder](https://github.com/tscharke/html-attribute-folder)

**Comment by tscharke** [comment]
Thanks @Flyrell 🙏
