### ISSUE TITLE
Compatibility with build 231.*

### ISSUE THREAD

**Issue by vandres** [Flyrell/html-attribute-folder#2]
Would it be possible to make this plugin compatible with newer builds?

**Comment by JulienVanelian** [comment]
I second this, would be great please!

**Comment by tscharke** [comment]
For this I created a [fork](https://github.com/tscharke/html-attribute-folder) and make it runnable 👉[https://github.com/tscharke/html-attribute-folder](https://github.com/tscharke/html-attribute-folder)

Or vote for this PR #5, so that @Flyrell integrates it 😃

**Comment by Flyrell** [comment]
Hey guys, thanks for opening the issues and trying to help.

I'm really sorry, but I don't have time to have any active development here. The code should still work, but unfortunately the need to update this plugin for every freaking version of IntelliJ is just terrible. If you have your won working forks, feel free to open the pull requests and I'm more than happy to review, merge and publish whatever makes sense. Thanks.
