### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by vandres** [Flyrell/html-attribute-folder#3]
Hi!

I made the plugin work for myself and colleagues with the latest versions of PS. I don't think the changes qualify for a PR, so I am thinking of publishing it under a different name. But since there is no license information, I don't wanne just "steal" your code.

Could you please add a lisense information to know how to use the code?

**Comment by Flyrell** [comment]
It's a MIT license. Sorry apparently I've added the license and forgot to ping this issue.
